#!/bin/python3

import math
import os
import random
import re
import sys
from collections import Counter

# Complete the freqQuery function below.
def freqQuery(queries):
    counts = Counter()
    counts_of_counts = Counter()
    out = []
    for query in queries:
        if query[0] == 1:
            counts_of_counts[counts[query[1]]] -= 1
            counts[query[1]] += 1
            counts_of_counts[counts[query[1]]] += 1
        elif query[0] == 2:
            if counts[query[1]] > 0:
                counts_of_counts[counts[query[1]]] -= 1
                counts[query[1]] -= 1
                counts_of_counts[counts[query[1]]] += 1
        else:
            if counts_of_counts[query[1]] > 0:
                out.append(1)
            else:
                out.append(0)
    return out
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    q = int(input().strip())

    queries = []

    for _ in range(q):
        queries.append(list(map(int, input().rstrip().split())))

    ans = freqQuery(queries)

    fptr.write('\n'.join(map(str, ans)))
    fptr.write('\n')

    fptr.close()
